name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Check Formatting & Linting
        run: bun run check

      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps chromium

      - name: Build & Run Tests
        run: bun run test:browser
